language: node_js
node_js:
  - '16.13.2'
branches:
  only:
    - trunk
cache:
  directories:
    - ./node_modules
addons:
  sonarcloud:
    organization: felipealvarez23
    token: c64191b586e3b3b4d3bada069d28a21ef46bc160
script:
  - npm test
  - sonar-scanner
